spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      continue-on-error: on
