CREATE TABLE IF NOT EXISTS AUTHORS(ID SERIAL PRIMARY KEY, INITIALS VARCHAR(50), LASTNAME VARCHAR(255), UNIQUE(INITIALS, LASTNAME));
CREATE TABLE IF NOT EXISTS BOOKS(ID SERIAL PRIMARY KEY, NAME VARCHAR(255), AUTHOR_ID INT REFERENCES AUTHORS(ID), UNIQUE(NAME, AUTHOR_ID));
CREATE TABLE IF NOT EXISTS GENRES(ID SERIAL PRIMARY KEY, NAME VARCHAR(255) UNIQUE);
CREATE TABLE IF NOT EXISTS BOOKS_GENRES(BOOK_ID INT REFERENCES BOOKS(ID), GENRE_ID INT REFERENCES GENRES(ID), PRIMARY KEY(BOOK_ID, GENRE_ID));
